"""init

Revision ID: a099bb46e9dd
Revises: 
Create Date: 2026-06-14 15:09:26.877036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a099bb46e9dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('external_message_id', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('onesignal_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'onesignal_id')
    op.drop_column('communications', 'external_message_id')
    # ### end Alembic commands ###
